name: geo_attendance_app
description: Geo Attendance App is a location-based attendance tracking system that ensures students are physically present in class before they can mark themselves as present.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.8.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  geolocator: ^13.0.2
  keyboard_dismisser: ^3.0.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.0
  rename: ^3.1.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

icons_launcher:
  image_path: 'assets/images/logo.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
